# Generated by Django 4.2 on 2023-09-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
